<?php

namespace Cocktails\RecipesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MeasureunitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeasureunitsRepository extends EntityRepository
{
    //$unit = new Measureunits();
   // $em = $this->getDoctrine()->getManager();

    //get unit list
    #$unitsRepository = $em->getRepository('CocktailsRecipesBundle:Measureunits');
    #$result = $unitsRepository->findAll(array('id', 'name'));
    #$query = $unitRepository->createQueryBuilder('p')->getQuery();
    #$unitList = $query->getArrayResult();

    public function get_measureunits_by_property(){

        $output = array();

        $query = $this->createQueryBuilder('a')->select('a.id, a.name')->where('a.name != :name')->setParameter('name', 'NULL')->getQuery();
        $unitList = $query->getResult();

        foreach($unitList as $unit){
            $output[$unit['id']] = $unit['name'];
        }

        return $output;

    }
}
