<?php

namespace Cocktails\RecipesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MeasureUnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeasureUnitRepository extends EntityRepository
{
}
