<?php

namespace Cocktails\RecipesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeRepository extends EntityRepository
{
    public function getFilteredRecipes($data, $type)
    {
        $em = $this->getEntityManager();
        $where = "";
        if($data != "")
            $where = "WHERE r.recipe".ucfirst($type)." IN($data)";

        $query = $em->createQuery(
            "
                            SELECT r
                            FROM Cocktails\RecipesBundle\Entity\Recipe r
                            $where
                        "
        );
        $recipes = $query->getResult();
        return $recipes;
    }
}
