<?php

namespace Cocktails\RecipesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsersIngredientsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersIngredientsRepository extends EntityRepository
{
    public function getUserIngredients($user){
        $em = $this->getEntityManager();


        $query = $em->createQuery(
            "
                            SELECT i
                            FROM Cocktails\RecipesBundle\Entity\Ingredient i
                            INNER JOIN i.users ui
                            WHERE ui.user = :user


                        "
        )->setParameters(array("user" => $user));
        $recipes = $query->getResult();
        return $recipes;
    }
}
