services:
    sonata.admin.recipes:
        class: Cocktails\RecipesBundle\Admin\RecipesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Recipes" }
        arguments:
            - ~
            - Cocktails\RecipesBundle\Entity\Recipes
            - ~
        calls:
            - [ setTranslationDomain, [CocktailsRecipesBundle]]

    sonata.admin.measureunits:
        class: Cocktails\RecipesBundle\Admin\MeasureunitsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Measure Units" }
        arguments:
            - ~
            - Cocktails\RecipesBundle\Entity\Measureunits
            - ~
        calls:
            - [ setTranslationDomain, [CocktailsRecipesBundle]]

    sonata.admin.ingredients:
        class: Cocktails\RecipesBundle\Admin\IngredientsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Ingredients" }
        arguments:
            - ~
            - Cocktails\RecipesBundle\Entity\Ingredients
            - ~
        calls:
            - [ setTranslationDomain, [CocktailsRecipesBundle]]