services:
    sonata.admin.recipe:
        class: Cocktails\RecipesBundle\Admin\RecipeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Recipes" }
        arguments:
            - ~
            - Cocktails\RecipesBundle\Entity\Recipe
            - ~
        calls:
            - [ setTranslationDomain, [CocktailsRecipesBundle]]

    sonata.admin.ingredient:
        class: Cocktails\RecipesBundle\Admin\IngredientAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Ingredients" }
        arguments:
            - ~
            - Cocktails\RecipesBundle\Entity\Ingredient
            - ~
        calls:
            - [ setTranslationDomain, [CocktailsRecipesBundle]]

    sonata.admin.measureunit:
        class: Cocktails\RecipesBundle\Admin\MeasureUnitAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Measure Units" }
        arguments:
            - ~
            - Cocktails\RecipesBundle\Entity\MeasureUnit
            - ~
        calls:
            - [ setTranslationDomain, [CocktailsRecipesBundle]]