services:
    sonata.admin.recipe:
        class: Cocktails\RecipesBundle\Admin\RecipeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Recipe" }
        arguments:
            - ~
            - Cocktails\RecipesBundle\Entity\Recipe
            - ~
        calls:
            - [ setTranslationDomain, [CocktailsRecipesBundle]]

    sonata.admin.ingredient:
        class: Cocktails\RecipesBundle\Admin\IngredientAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Ingredient" }
        arguments:
            - ~
            - Cocktails\RecipesBundle\Entity\Ingredient
            - ~
        calls:
            - [ setTranslationDomain, [CocktailsRecipesBundle]]

    sonata.admin.measureunit:
        class: Cocktails\RecipesBundle\Admin\MeasureUnitAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Measure Unit" }
        arguments:
            - ~
            - Cocktails\RecipesBundle\Entity\MeasureUnit
            - ~
        calls:
            - [ setTranslationDomain, [CocktailsRecipesBundle]]

    sonata.admin.recipetaste:
        class: Cocktails\RecipesBundle\Admin\RecipeTasteAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Recipe Taste" }
        arguments:
            - ~
            - Cocktails\RecipesBundle\Entity\RecipeTaste
            - ~
        calls:
            - [ setTranslationDomain, [CocktailsRecipesBundle]]

    sonata.admin.recipetype:
        class: Cocktails\RecipesBundle\Admin\RecipeTypeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Recipe Type" }
        arguments:
            - ~
            - Cocktails\RecipesBundle\Entity\RecipeType
            - ~
        calls:
            - [ setTranslationDomain, [CocktailsRecipesBundle]]

    sonata.admin.image:
        class: Cocktails\RecipesBundle\Admin\ImageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Image" }
        arguments:
            - ~
            - Cocktails\RecipesBundle\Entity\Image
            - ~
        calls:
            - [ setTranslationDomain, [CocktailsRecipesBundle]]

    sonata.admin.user:
            class: Cocktails\RecipesBundle\Admin\UserAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: "Content", label: "User" }
            arguments:
                - ~
                - Cocktails\RecipesBundle\Entity\User
                - ~
            calls:
                - [ setTranslationDomain, [CocktailsRecipesBundle]]

#    sonata.admin.recipesingredients:
#            class: Cocktails\RecipesBundle\Admin\RecipesIngredientsAdmin
#            tags:
#                - { name: sonata.admin, manager_type: orm, group: "Content", label: "Recipes/Ingredients" }
#            arguments:
#                - ~
#                - Cocktails\RecipesBundle\Entity\RecipesIngredients
#                - ~
#            calls:
#                - [ setTranslationDomain, [CocktailsRecipesBundle]]
