cocktails_recipes_homepage:
    pattern:  /
    defaults: { _controller: CocktailsRecipesBundle:Default:index }

cocktails_recipes_list:
    pattern:  /list
    defaults: { _controller: CocktailsRecipesBundle:Default:list }

cocktails_recipes_table:
    pattern: /table
    defaults: {_controller: CocktailsRecipesBundle:Default:recipeTable }

cocktails_recipes_menu:
    pattern: /menu
    defaults: {_controller: CocktailsRecipesBundle:Default:menu }

cocktails_recipes_taste:
    pattern: /tasteSort
    defaults: {_controller: CocktailsRecipesBundle:Navigation:tasteSort}

cocktails_recipes_type:
    pattern: /typeSort
    defaults: {_controller: CocktailsRecipesBundle:Navigation:typeSort}

cocktails_recipe_single:
    pattern: /Recipe/{id}
    defaults: {_controller: CocktailsRecipesBundle:Navigation:showRecipe, id: id}

cocktails_my_products:
    pattern: /myProducts
    defaults: {_controller: CocktailsRecipesBundle:Navigation:myProducts}

cocktails_my_recipes:
    pattern: /myRecipes
    defaults: {_controller: CocktailsRecipesBundle:Navigation:myRecipes}

cocktails_add_ingredient:
    pattern: /ajax
    defaults: {_controller: CocktailsRecipesBundle:Button:addIngredientToUser}

cocktails_remove_ingredient:
    pattern: /ajaxRemoveIngr
    defaults: {_controller: CocktailsRecipesBundle:Button:removeIngredientFromUser}

cocktails_add_recipe_to_user:
    pattern: /ajaxAddRecipe
    defaults: {_controller: CocktailsRecipesBundle:Button:addRecipeToUser}

cocktails_remove_recipe:
    pattern: /ajaxRemoveRec
    defaults: {_controller: CocktailsRecipesBundle:Button:removeRecipeFromUser}