Cocktails\RecipesBundle\Entity\Image:
    properties:
        file:
            - File:
                maxSize: 6000000

Cocktails\RecipesBundle\Entity\Ingredient:
    properties:
        file:
            - File:
                maxSize: 6000000